export const ALERT_SET = 'ALERT_SET';
export const ALERT_REMOVE = 'ALERT_REMOVE';
export const GET_ADMIN = 'GET_ADMIN';
export const REG_ADMIN = 'REG_ADMIN';
export const AUTH_ADMIN = 'AUTH_ADMIN';
export const ADMIN_FAIL = 'ADMIN_FAIL';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const ADMIN_ERROR = 'ADMIN_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const GET_CONSUMER = 'GET_CONSUMER';
export const REG_CONSUMER = 'REG_CONSUMER';
export const AUTH_CONSUMER = 'AUTH_CONSUMER';
export const LOADED_CONSUMER = 'LOADED_CONSUMER';
export const ERROR_CONSUMER = 'ERROR_CONSUMER';
export const FAIL_CONSUMER = 'FAIL_CONSUMER';
export const LOGOUT_CONSUMER = 'LOGOUT_CONSUMER';

export const CATEGORY_CREATE = 'CATEGORY_CREATE';
export const CATEGORY_GET = 'CATEGORY_GET';
export const CATEGORIES_GET = 'CATEGORIES_GET';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_GET = 'PRODUCT_GET';
export const PRODUCTS_GET = 'PRODUCTS_GET';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
